import FWCore.ParameterSet.Config as cms

singElecCRNoJetSelSkimFilter_ = cms.EDFilter ("singElecCRNoJetSelSkim",
    vertices = cms.InputTag("offlineSlimmedPrimaryVertices",""),
    leptons = cms.InputTag("slimmedElectrons",""),
    tracks = cms.InputTag("isolatedTracks",""),
    jets = cms.InputTag("slimmedJets",""),
    mets = cms.InputTag("slimmedMETs",""),
    pfCandidates = cms.InputTag("packedPFCandidates",""),
    triggersPAT = cms.InputTag('TriggerResults','','PAT'),
    triggersHLT = cms.InputTag('TriggerResults','','HLT'),
    HLTName = cms.string('HLT_Ele32_WPTight_Gsf_v'),
    isCRAB = cms.bool(False),
    isMETTriggers = cms.bool(False),
    trigobjs = cms.InputTag('slimmedPatTrigger'),
    ecalBadCalibReducedMINIAODFilter = cms.InputTag('ecalBadCalibReducedMINIAODFilter'),
)

singMuonCRNoJetSelSkimFilter_ = cms.EDFilter ("singMuonCRNoJetSelSkim",
    vertices = cms.InputTag("offlineSlimmedPrimaryVertices",""),
    leptons = cms.InputTag("slimmedMuons",""),
    tracks = cms.InputTag("isolatedTracks",""),
    jets = cms.InputTag("slimmedJets",""),
    mets = cms.InputTag("slimmedMETs",""),
    pfCandidates = cms.InputTag("packedPFCandidates",""),
    triggersPAT = cms.InputTag('TriggerResults','','PAT'),
    triggersHLT = cms.InputTag('TriggerResults','','HLT'),
    HLTName = cms.string('HLT_IsoMu24_v'),
    isCRAB = cms.bool(False),
    isMETTriggers = cms.bool(False),
    trigobjs = cms.InputTag('slimmedPatTrigger'),
    ecalBadCalibReducedMINIAODFilter = cms.InputTag('ecalBadCalibReducedMINIAODFilter'),
)

singTauCRNoJetSelSkimFilter_ = cms.EDFilter ("singTauCRNoJetSelSkim",
    vertices = cms.InputTag("offlineSlimmedPrimaryVertices",""),
    leptons = cms.InputTag("slimmedTaus",""),
    tracks = cms.InputTag("isolatedTracks",""),
    jets = cms.InputTag("slimmedJets",""),
    mets = cms.InputTag("slimmedMETs",""),
    pfCandidates = cms.InputTag("packedPFCandidates",""),
    triggersPAT = cms.InputTag('TriggerResults','','PAT'),
    triggersHLT = cms.InputTag('TriggerResults','','HLT'),
    HLTName = cms.string('HLT_IsoMu24_eta2p1_MediumDeepTauPFTauHPS20_eta2p1_SingleL1_v'),
    isCRAB = cms.bool(False),
    isMETTriggers = cms.bool(False),
    trigobjs = cms.InputTag('slimmedPatTrigger'),
    ecalBadCalibReducedMINIAODFilter = cms.InputTag('ecalBadCalibReducedMINIAODFilter'),
)