#include "tdrstyle.C"
#include "CMS_lumi.C"

void create_efficiencies_2files()
{
    setTDRStyle();

    gStyle->SetOptStat(0);

    writeExtraText = true;
    extraText = "Work in Progress";
    // lumi_sqrtS = dataset + " - " + file1 + " vs " + file2;
    lumi_sqrtS = "34.7 fb^{-1}, 13.6 TeV";

    std::string inputFile1 = "plots/right_Muon_2022.root";
    std::string inputFile2 = "plots/right_WToLNu_2022.root";
    TFile *f1 = TFile::Open(inputFile1.c_str());
    TFile *f2 = TFile::Open(inputFile2.c_str());

    TGraphAsymmErrors *hltTrk50Filter_file1;
    TGraphAsymmErrors *hltTrk50Filter_file2;
    f1->GetObject("Graph;15", hltTrk50Filter_file1);
    f2->GetObject("Graph;15", hltTrk50Filter_file2);

    TGraphAsymmErrors *MET105_file1;
    TGraphAsymmErrors *MET105_file2;
    f1->GetObject("Graph;4", MET105_file1);
    f2->GetObject("Graph;4", MET105_file2);

    TGraphAsymmErrors *hltMET105_file1;
    TGraphAsymmErrors *hltMET105_file2;
    f1->GetObject("Graph;5", hltMET105_file1);
    f2->GetObject("Graph;5", hltMET105_file2);

    TGraphAsymmErrors *GrandOR_file1;
    TGraphAsymmErrors *GrandOR_file2;
    f1->GetObject("Graph;6", GrandOR_file1);
    f2->GetObject("Graph;6", GrandOR_file2);

    TGraphAsymmErrors *GrandORExcept_file1;
    TGraphAsymmErrors *GrandORExcept_file2;
    f1->GetObject("Graph;7", GrandORExcept_file1);
    f2->GetObject("Graph;7", GrandORExcept_file2);

    TGraphAsymmErrors *GrandORExceptIsoTrk_file1;
    TGraphAsymmErrors *GrandORExceptIsoTrk_file2;
    f1->GetObject("Graph;6", GrandORExceptIsoTrk_file1);
    f1->GetObject("Graph;8", GrandORExceptIsoTrk_file2);
    
    int marker = 20;
    const char *ylabel = "Trigger Efficiency";
    const char *xlabelnomu = "PF E_{T}^{miss, no mu}";
    const char *xlabelyemu = "PF E_{T}^{miss}";
    const char *xlabelmupt = "muon p_{T}";
    float ymin = 0.0;
    float ymax = 1.2;
    float xmin = 0.0;
    float xmax = 1000.0;
    TLine *l = new TLine(xmin, 1.0, xmax, 1.0);
    l->SetLineStyle(7);
    l->SetLineWidth(2);
    float x0 = 0.1891;
    float x1 = 0.3395;
    float y0 = 0.8392;
    float y1 = 0.9214;
    // std::string legend_file1 = dataset + " " + file1;
    // std::string legend_file2 = dataset + " " + file2;
    std::string legend_file1 = "2022 data";
    std::string legend_file2 = "W -> lv 2022 MC";

    TCanvas *c1 = new TCanvas("c1", "c1", 700, 700);
    TCanvas *c2 = new TCanvas("c2", "c2", 700, 700);
    TCanvas *c3 = new TCanvas("c3", "c3", 700, 700);
    TCanvas *c4 = new TCanvas("c4", "c4", 700, 700);
    TCanvas *c5 = new TCanvas("c5", "c5", 700, 700);
    TCanvas *c6 = new TCanvas("c6", "c6", 700, 700);

    std::string outFile = "plots/Plots_TriggerEffs_Muon2022/2022_hlt_effs_comp.root";
    TFile *file = new TFile(outFile.c_str(), "RECREATE");

    c1->cd();
    hltTrk50Filter_file1->GetHistogram()->SetMinimum(ymin);
    hltTrk50Filter_file1->GetHistogram()->SetMaximum(ymax);
    hltTrk50Filter_file1->GetYaxis()->SetTitle(ylabel);
    hltTrk50Filter_file1->GetXaxis()->SetTitle(xlabelmupt);
    hltTrk50Filter_file1->GetYaxis()->SetTitleSize(0.04);
    hltTrk50Filter_file1->GetXaxis()->SetTitleSize(0.04);
    hltTrk50Filter_file1->GetYaxis()->SetLabelSize(0.04);
    hltTrk50Filter_file1->GetXaxis()->SetLabelSize(0.04);
    hltTrk50Filter_file1->GetXaxis()->SetLimits(xmin, xmax);
    hltTrk50Filter_file1->SetMarkerStyle(marker);
    hltTrk50Filter_file1->SetTitle("");
    hltTrk50Filter_file2->SetMarkerColor(1);
    hltTrk50Filter_file2->SetMarkerStyle(marker);
    hltTrk50Filter_file2->SetMarkerColor(4);
    hltTrk50Filter_file2->SetLineColor(4);
    auto legend1 = new TLegend(x0, y0, x1, y1);
    legend1->AddEntry(hltTrk50Filter_file1, legend_file1.c_str(), "P");
    legend1->AddEntry(hltTrk50Filter_file2, legend_file2.c_str(), "P");
    legend1->SetLineWidth(0);
    legend1->SetTextSize(0.02559);
    legend1->SetBorderSize(0);
    legend1->SetTextFont(42);
    legend1->SetHeader("hltTrk50Filter");
    hltTrk50Filter_file1->Draw("AP");
    hltTrk50Filter_file2->Draw("P,SAME");
    legend1->Draw();
    l->Draw();
    CMS_lumi(c1, 0, 0);
    c1->Update();
    c1->Write();
    std::string c1Name = "plots/Plots_TriggerEffs_Muon2022/2022_hltTrk50Filter.pdf";
    c1->Print(c1Name.c_str());

    c2->cd();
    MET105_file1->GetHistogram()->SetMinimum(ymin);
    MET105_file1->GetHistogram()->SetMaximum(ymax);
    MET105_file1->GetYaxis()->SetTitle(ylabel);
    MET105_file1->GetXaxis()->SetTitle(xlabelnomu);
    MET105_file1->GetYaxis()->SetTitleSize(0.04);
    MET105_file1->GetXaxis()->SetTitleSize(0.04);
    MET105_file1->GetYaxis()->SetLabelSize(0.04);
    MET105_file1->GetXaxis()->SetLabelSize(0.04);
    MET105_file1->GetXaxis()->SetLimits(xmin, xmax);
    MET105_file1->SetMarkerStyle(marker);
    MET105_file1->SetTitle("");
    MET105_file2->SetMarkerColor(1);
    MET105_file2->SetMarkerStyle(marker);
    MET105_file2->SetMarkerColor(4);
    MET105_file2->SetLineColor(4);
    auto legend2 = new TLegend(x0, y0, x1, y1);
    legend2->AddEntry(MET105_file1, legend_file1.c_str(), "P");
    legend2->AddEntry(MET105_file2, legend_file2.c_str(), "P");
    legend2->SetLineWidth(0);
    legend2->SetTextSize(0.02559);
    legend2->SetBorderSize(0);
    legend2->SetTextFont(42);
    legend2->SetHeader("HLT_MET105_IsoTrk50");
    MET105_file1->Draw("AP");
    MET105_file2->Draw("P,SAME");
    legend2->Draw();
    l->Draw();
    CMS_lumi(c2, 0, 0);
    c2->Update();
    c2->Write();
    std::string c2Name = "plots/Plots_TriggerEffs_Muon2022/2022_HLT_MET105_IsoTrk50.pdf";
    c2->Print(c2Name.c_str());

    c3->cd();
    hltMET105_file1->GetHistogram()->SetMinimum(ymin);
    hltMET105_file1->GetHistogram()->SetMaximum(ymax);
    hltMET105_file1->GetYaxis()->SetTitle(ylabel);
    hltMET105_file1->GetXaxis()->SetTitle(xlabelnomu);
    hltMET105_file1->GetYaxis()->SetTitleSize(0.04);
    hltMET105_file1->GetXaxis()->SetTitleSize(0.04);
    hltMET105_file1->GetYaxis()->SetLabelSize(0.04);
    hltMET105_file1->GetXaxis()->SetLabelSize(0.04);
    hltMET105_file1->GetXaxis()->SetLimits(xmin, xmax);
    hltMET105_file1->SetMarkerStyle(marker);
    hltMET105_file1->SetTitle("");
    hltMET105_file2->SetMarkerColor(1);
    hltMET105_file2->SetMarkerStyle(marker);
    hltMET105_file2->SetMarkerColor(4);
    hltMET105_file2->SetLineColor(4);
    auto legend3 = new TLegend(x0, y0, x1, y1);
    legend3->AddEntry(hltMET105_file1, legend_file1.c_str(), "P");
    legend3->AddEntry(hltMET105_file2, legend_file2.c_str(), "P");
    legend3->SetLineWidth(0);
    legend3->SetTextSize(0.02559);
    legend3->SetBorderSize(0);
    legend3->SetTextFont(42);
    legend3->SetHeader("hltMET105");
    hltMET105_file1->Draw("AP");
    hltMET105_file2->Draw("P,SAME");
    legend3->Draw();
    l->Draw();
    CMS_lumi(c3, 0, 0);
    c3->Update();
    c3->Write();
    std::string c3Name = "plots/Plots_TriggerEffs_Muon2022/2022_hltMET105.pdf";
    c3->Print(c3Name.c_str());

    c4->cd();
    GrandOR_file1->GetHistogram()->SetMinimum(ymin);
    GrandOR_file1->GetHistogram()->SetMaximum(ymax);
    GrandOR_file1->GetYaxis()->SetTitle(ylabel);
    GrandOR_file1->GetXaxis()->SetTitle(xlabelnomu);
    GrandOR_file1->GetYaxis()->SetTitleSize(0.04);
    GrandOR_file1->GetXaxis()->SetTitleSize(0.04);
    GrandOR_file1->GetYaxis()->SetLabelSize(0.04);
    GrandOR_file1->GetXaxis()->SetLabelSize(0.04);
    GrandOR_file1->GetXaxis()->SetLimits(xmin, xmax);
    GrandOR_file1->SetMarkerStyle(marker);
    GrandOR_file1->SetTitle("");
    GrandOR_file2->SetMarkerColor(1);
    GrandOR_file2->SetMarkerStyle(marker);
    GrandOR_file2->SetMarkerColor(4);
    GrandOR_file2->SetLineColor(4);
    auto legend4 = new TLegend(x0, y0, x1, y1);
    legend4->AddEntry(GrandOR_file1, legend_file1.c_str(), "P");
    legend4->AddEntry(GrandOR_file2, legend_file2.c_str(), "P");
    legend4->SetLineWidth(0);
    legend4->SetTextSize(0.02559);
    legend4->SetBorderSize(0);
    legend4->SetTextFont(42);
    legend4->SetHeader("GrandOR");
    GrandOR_file1->Draw("AP");
    GrandOR_file2->Draw("P,SAME");
    legend4->Draw();
    l->Draw();
    CMS_lumi(c4, 0, 0);
    c4->Update();
    c4->Write();
    std::string c4Name = "plots/Plots_TriggerEffs_Muon2022/2022_GrandOR.pdf";
    c4->Print(c4Name.c_str());

    c5->cd();
    GrandORExcept_file1->GetHistogram()->SetMinimum(ymin);
    GrandORExcept_file1->GetHistogram()->SetMaximum(ymax);
    GrandORExcept_file1->GetYaxis()->SetTitle(ylabel);
    GrandORExcept_file1->GetXaxis()->SetTitle(xlabelnomu);
    GrandORExcept_file1->GetYaxis()->SetTitleSize(0.04);
    GrandORExcept_file1->GetXaxis()->SetTitleSize(0.04);
    GrandORExcept_file1->GetYaxis()->SetLabelSize(0.04);
    GrandORExcept_file1->GetXaxis()->SetLabelSize(0.04);
    GrandORExcept_file1->GetXaxis()->SetLimits(xmin, xmax);
    GrandORExcept_file1->SetMarkerStyle(marker);
    GrandORExcept_file1->SetTitle("");
    GrandORExcept_file2->SetMarkerColor(1);
    GrandORExcept_file2->SetMarkerStyle(marker);
    GrandORExcept_file2->SetMarkerColor(4);
    GrandORExcept_file2->SetLineColor(4);
    auto legend5 = new TLegend(x0, y0, x1, y1);
    legend5->AddEntry(GrandORExcept_file1, legend_file1.c_str(), "P");
    legend5->AddEntry(GrandORExcept_file2, legend_file2.c_str(), "P");
    legend5->SetLineWidth(0);
    legend5->SetTextSize(0.02559);
    legend5->SetBorderSize(0);
    legend5->SetTextFont(42);
    legend5->SetHeader("GrandOR except HLT_PFMETNoMu110_PFMHTNoMu110_IDTight_FilterHF");
    GrandORExcept_file1->Draw("AP");
    GrandORExcept_file2->Draw("P,SAME");
    legend5->Draw();
    l->Draw();
    CMS_lumi(c5, 0, 0);
    c5->Update();
    c5->Write();
    std::string c5Name = "plots/Plots_TriggerEffs_Muon2022/2022_GrandORExcept.pdf";
    c5->Print(c5Name.c_str());

    c6->cd();
    GrandORExceptIsoTrk_file1->GetHistogram()->SetMinimum(ymin);
    GrandORExceptIsoTrk_file1->GetHistogram()->SetMaximum(ymax);
    GrandORExceptIsoTrk_file1->GetYaxis()->SetTitle(ylabel);
    GrandORExceptIsoTrk_file1->GetXaxis()->SetTitle(xlabelnomu);
    GrandORExceptIsoTrk_file1->GetYaxis()->SetTitleSize(0.04);
    GrandORExceptIsoTrk_file1->GetXaxis()->SetTitleSize(0.04);
    GrandORExceptIsoTrk_file1->GetYaxis()->SetLabelSize(0.04);
    GrandORExceptIsoTrk_file1->GetXaxis()->SetLabelSize(0.04);
    GrandORExceptIsoTrk_file1->GetXaxis()->SetLimits(xmin, xmax);
    GrandORExceptIsoTrk_file1->SetMarkerStyle(marker);
    GrandORExceptIsoTrk_file1->SetTitle("");
    GrandORExceptIsoTrk_file2->SetMarkerColor(1);
    GrandORExceptIsoTrk_file2->SetMarkerStyle(marker);
    GrandORExceptIsoTrk_file2->SetMarkerColor(4);
    GrandORExceptIsoTrk_file2->SetLineColor(4);
    auto legend6 = new TLegend(x0, y0, x1, y1);
    legend6->AddEntry(GrandORExceptIsoTrk_file1, "GrandOR", "P");
    legend6->AddEntry(GrandORExceptIsoTrk_file2, "GrandOR except MET+IsoTrk paths", "P");
    legend6->SetLineWidth(0);
    legend6->SetTextSize(0.02559);
    legend6->SetBorderSize(0);
    legend6->SetTextFont(42);
    legend6->SetHeader("Muon 2022");
    GrandORExceptIsoTrk_file1->Draw("AP");
    GrandORExceptIsoTrk_file2->Draw("P,SAME");
    legend6->Draw();
    l->Draw();
    CMS_lumi(c6, 0, 0);
    c6->Update();
    c6->Write();
    std::string c6Name = "plots/Plots_TriggerEffs_Muon2022/2022_GrandORExceptIsoTrk.pdf";
    c6->Print(c6Name.c_str());

    f1->Close();
    f2->Close();
    file->Close();
}